name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "26.2"
          elixir-version: "1.15.7"

      - name: Install deps (root)
        run: mix deps.get

      - name: Check format (root)
        run: mix format --check-formatted

      - name: Run tests (root)
        run: mix test

      - name: Install deps (demo)
        run: mix deps.get
        working-directory: demo

      - name: Check format (demo)
        run: mix format --check-formatted
        working-directory: demo

      - name: Run tests (demo)
        run: mix test
        working-directory: demo
